name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
      - uses: actions/checkout@v4
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{0}, {1}.', 'Hi', 'world') }}
          JOIN_FUNC: ${{ join(github.event.*.html_url, ',') }}