name: Hello
run-name: "3.9.1"
on: push
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      - env:
          RESULT: ${{ steps.source.outputs.result }}
        run: echo "${RESULT}"